<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace enrol_poodlllti\task;

use core\task\scheduled_task;
use enrol_lti\local\ltiadvantage\entity\application_registration;
use enrol_poodlllti\util;
use enrol_poodlllti_generator;
use phpunit_util;

/**
 * Class autogenerate
 *
 * @package    enrol_poodlllti
 * @copyright  2026 Justin Hunt (poodllsupport@gmail.com)
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class autogeneratedata extends scheduled_task {

    public const DATACOUNTS = [
        'platform' => 5,
        'category' => 5,
        'course' => 5,
        'newcategorycourse' => 10,
    ];

    const PLATFORM_NAME = 'unassigned platform';

    const TENANT_NAME = 'unassigned tenant';

    const TENANT_COURSE_NAME = 'unassigned course tenant';

    /**
     * Get the name of task.
     * @return string
     */
    public function get_name(): string {
        return get_string('autogeneratedatatask', util::COMPONENT);
    }

    /**
     * Perfome task to autogenerate category and platform.
     * @return void
     */
    public function execute() {
        global $DB;

        mtrace('Auto generate data task run started');

        $platformscount = $DB->count_records_select(
            'enrol_lti_app_registration',
            'clientid IS NULL AND status = :incomplete',
            ['incomplete' => application_registration::REGISTRATION_STATUS_INCOMPLETE]
        );

        mtrace('Unassigned platforms count : ' . $platformscount);

        if ($platformscount < self::DATACOUNTS['platform']) {
            $platformcreatecount = self::DATACOUNTS['platform'] - $platformscount;
            mtrace('Creating a ' . $platformcreatecount. ' new platforms');
            $this->generate_platforms($platformcreatecount);
        }

        $categoriescount = $DB->count_records_select(
            'course_categories',
            "parent = 0 AND visible = 1 AND COALESCE(idnumber, '') = ''"
        );

        mtrace('Unassigned categories count : ' . $categoriescount);

        if ($categoriescount < self::DATACOUNTS['category']) {
            $categorycreatecount = self::DATACOUNTS['category'] - $categoriescount;
            mtrace('Creating a ' . $categorycreatecount. ' new categories');
            $this->generate_categories($categorycreatecount);
        }

        $clcategories = $DB->get_records_sql(
            "SELECT cc.id FROM {course_categories} cc
            JOIN {enrol_poodlllti_clients} cl ON cl.categoryid = cc.id
            WHERE cc.visible = 1 AND cc.parent = 0 AND cc.idnumber != ''
            AND COALESCE(cl.deleted, 0) = 0
            GROUP BY cc.id",
        );

        foreach ($clcategories as $clcategory) {
            mtrace('Checking course count of category : ' . $clcategory->id);
            $unusedcoursecount = $DB->count_records_select(
                'course',
                "category = :categoryid AND visible = 1 AND COALESCE(idnumber, '') = ''",
                ['categoryid' => $clcategory->id]
            );
            mtrace('Unused course count : ' . $unusedcoursecount);
            if ($unusedcoursecount < self::DATACOUNTS['course']) {
                $coursecreatecount = self::DATACOUNTS['course'] - $unusedcoursecount;
                mtrace('Creating a ' . $coursecreatecount. ' new courses');
                $this->generate_courses($clcategory->id, $coursecreatecount);
            }
        }

    }

    public function get_generator(): enrol_poodlllti_generator {
        global $CFG;
        require_once($CFG->libdir . '/phpunit/classes/util.php');
        return phpunit_util::get_data_generator()->get_plugin_generator(util::COMPONENT);
    }

    public function generate_platforms($count = self::DATACOUNTS['platform']) {
        for ($i = 0; $i < $count; $i++) {
            $platform = $this->get_generator()->create_application_registration([
                'name' => self::PLATFORM_NAME
            ]);
            mtrace('New platformid : ' . $platform->get_id());
        }
        return;
    }

    public function generate_categories($count = self::DATACOUNTS['category']) {
        for ($i = 0; $i < $count; $i++) {
            $this->create_course_category();
        }
    }

    public function create_course_category() {
        $categorygenerator = $this->get_generator();
        $newcategory = $categorygenerator->create_empty_category();
        mtrace('New categoryid : ' . $newcategory->id);
        if ($newcategory) {
            $this->generate_courses($newcategory->id, self::DATACOUNTS['newcategorycourse']);
        }
        return;
    }

    public function generate_courses($categoryid, $createcount = self::DATACOUNTS['course']) {
        $coursegenerator = $this->get_generator();
        $record = ['category' => $categoryid];
        for ($i = 0; $i < $createcount; $i++) {
            $course = $coursegenerator->create_empty_course($record);
            mtrace('New courseid : ' . $course->id);
        }
        return;
    }

}
